name: Build

on:
  push:
    branches:
    - ux
  pull_request:
    branches:
    - ux


env:
  CI: true
  node: 12.x
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ env.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node }}
    - name: Install & build
      run: |
        yarn install
        yarn build:ssr
    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Zip artifacts
      env:
        TAG_NAME: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      run: |
        mkdir artifacts
        zip -r artifacts/storefront-ux.zip dist
    - uses: actions/upload-artifact@v1
      with:
        name: storefront-ux.zip
        path: artifacts/storefront-ux.zip
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "artifacts/storefront-ux.zip"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
